// GRAINSKART Constants

export const APP_NAME = "GRAINSKART";
export const APP_TAGLINE = "Fresh Flavors, Fast Delivery";

// Mock data for demo
export const MOCK_CATEGORIES = [
  { id: "1", name: "Pizza", slug: "pizza", image_url: "/placeholder.svg" },
  { id: "2", name: "Burgers", slug: "burgers", image_url: "/placeholder.svg" },
  { id: "3", name: "Biryani", slug: "biryani", image_url: "/placeholder.svg" },
  { id: "4", name: "Chinese", slug: "chinese", image_url: "/placeholder.svg" },
  { id: "5", name: "Desserts", slug: "desserts", image_url: "/placeholder.svg" },
  { id: "6", name: "South Indian", slug: "south-indian", image_url: "/placeholder.svg" },
  { id: "7", name: "North Indian", slug: "north-indian", image_url: "/placeholder.svg" },
  { id: "8", name: "Healthy", slug: "healthy", image_url: "/placeholder.svg" },
];

export const MOCK_RESTAURANTS = [
  {
    id: "1",
    name: "Royal Biryani House",
    slug: "royal-biryani-house",
    cuisine_type: ["Biryani", "North Indian", "Mughlai"],
    rating: 4.5,
    total_reviews: 1250,
    delivery_time_min: 25,
    delivery_time_max: 35,
    price_range: 2,
    is_veg_only: false,
    is_featured: true,
    image_url: "/placeholder.svg",
    address: "MG Road, Bangalore",
    min_order_amount: 150,
    delivery_fee: 40,
  },
  {
    id: "2",
    name: "Green Leaf Cafe",
    slug: "green-leaf-cafe",
    cuisine_type: ["Healthy", "Salads", "Smoothies"],
    rating: 4.3,
    total_reviews: 890,
    delivery_time_min: 20,
    delivery_time_max: 30,
    price_range: 3,
    is_veg_only: true,
    is_featured: true,
    image_url: "/placeholder.svg",
    address: "Koramangala, Bangalore",
    min_order_amount: 200,
    delivery_fee: 35,
  },
  {
    id: "3",
    name: "Dragon Wok",
    slug: "dragon-wok",
    cuisine_type: ["Chinese", "Thai", "Asian"],
    rating: 4.2,
    total_reviews: 650,
    delivery_time_min: 30,
    delivery_time_max: 45,
    price_range: 2,
    is_veg_only: false,
    is_featured: false,
    image_url: "/placeholder.svg",
    address: "HSR Layout, Bangalore",
    min_order_amount: 100,
    delivery_fee: 45,
  },
  {
    id: "4",
    name: "Pizza Paradise",
    slug: "pizza-paradise",
    cuisine_type: ["Pizza", "Italian", "Pasta"],
    rating: 4.6,
    total_reviews: 2100,
    delivery_time_min: 25,
    delivery_time_max: 35,
    price_range: 2,
    is_veg_only: false,
    is_featured: true,
    image_url: "/placeholder.svg",
    address: "Indiranagar, Bangalore",
    min_order_amount: 199,
    delivery_fee: 30,
  },
  {
    id: "5",
    name: "South Spice",
    slug: "south-spice",
    cuisine_type: ["South Indian", "Kerala", "Tamil"],
    rating: 4.4,
    total_reviews: 780,
    delivery_time_min: 20,
    delivery_time_max: 30,
    price_range: 1,
    is_veg_only: true,
    is_featured: false,
    image_url: "/placeholder.svg",
    address: "Whitefield, Bangalore",
    min_order_amount: 100,
    delivery_fee: 40,
  },
  {
    id: "6",
    name: "Burger Barn",
    slug: "burger-barn",
    cuisine_type: ["Burgers", "American", "Fast Food"],
    rating: 4.1,
    total_reviews: 1450,
    delivery_time_min: 15,
    delivery_time_max: 25,
    price_range: 2,
    is_veg_only: false,
    is_featured: true,
    image_url: "/placeholder.svg",
    address: "JP Nagar, Bangalore",
    min_order_amount: 150,
    delivery_fee: 35,
  },
];

export const MOCK_MENU_ITEMS = [
  {
    id: "1",
    restaurant_id: "1",
    name: "Hyderabadi Chicken Biryani",
    description: "Aromatic basmati rice layered with tender chicken, slow-cooked with authentic spices",
    price: 299,
    discounted_price: 249,
    is_veg: false,
    is_bestseller: true,
    image_url: "/placeholder.svg",
  },
  {
    id: "2",
    restaurant_id: "1",
    name: "Mutton Biryani Special",
    description: "Premium mutton pieces cooked in dum style with fragrant rice",
    price: 399,
    discounted_price: null,
    is_veg: false,
    is_bestseller: true,
    image_url: "/placeholder.svg",
  },
  {
    id: "3",
    restaurant_id: "1",
    name: "Veg Biryani",
    description: "Mixed vegetables with aromatic rice and special biryani masala",
    price: 199,
    discounted_price: 179,
    is_veg: true,
    is_bestseller: false,
    image_url: "/placeholder.svg",
  },
  {
    id: "4",
    restaurant_id: "4",
    name: "Margherita Pizza",
    description: "Classic pizza with fresh mozzarella, tomatoes, and basil",
    price: 299,
    discounted_price: null,
    is_veg: true,
    is_bestseller: true,
    image_url: "/placeholder.svg",
  },
  {
    id: "5",
    restaurant_id: "4",
    name: "Pepperoni Pizza",
    description: "Loaded with spicy pepperoni and melted cheese",
    price: 399,
    discounted_price: 349,
    is_veg: false,
    is_bestseller: true,
    image_url: "/placeholder.svg",
  },
];
